# Try to find the opencv2 lib and include files
#
# OPENCV2_INCLUDE_DIR
# OPENCV2_LIBRARIES
# OPENCV2_FOUND

FIND_PATH( OPENCV2_INCLUDE_DIR opencv2/highgui
  /usr/include
  /usr/local/include
)

FIND_LIBRARY( OPENCV2_LIBRARY opencv2
  /usr/lib64
  /usr/lib
  /usr/local/lib
)

IF(OPENCV2_INCLUDE_DIR AND OPENCV2_LIBRARY)
  SET( OPENCV2_FOUND TRUE )
  SET( OPENCV2_LIBRARIES ${OPENCV2_LIBRARY} )
ENDIF(OPENCV2_INCLUDE_DIR AND OPENCV2_LIBRARY)

IF(OPENCV2_FOUND)
   IF(NOT OPENCV2_FIND_QUIETLY)
      MESSAGE(STATUS "Found OPENCV2: ${OPENCV2_LIBRARY}")
   ENDIF(NOT OPENCV2_FIND_QUIETLY)
ELSE(OPENCV2_FOUND)
   IF(OPENCV2_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find opencv2")
   ENDIF(OPENCV2_FIND_REQUIRED)
ENDIF(OPENCV2_FOUND)

